---
name: Conventional commits

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  title:
    name: Conventional commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: doomspork/action-conventional-commits@master
        with:
          include-pull-request-title: true
